#!/usr/bin/env python

from lxml import html
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "fuzziverse.settings")
from fuzziverse import models
t = html.parse("http://lcamtuf.coredump.cx/afl/")
for entry in t.xpath('//td'):
        name = entry.text.strip()
        app, created = models.Application.objects.get_or_create(name=name)
        print("Adding: %s" % name)
        for link in entry.xpath('.//a'):
                report = models.Report()
                report.app = app
                report.title = "(autogenerated from Lcamtuf's page)"
                report.url = link.get('href')
                report.save()
