#!/usr/bin/env python

from lxml import html
import urllib
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "fuzziverse.settings")
from fuzziverse import models
t = html.parse(urllib.urlopen("https://fuzzing-project.org/software.html"))
for entry in t.xpath('//tr/td/a/../..'):
        name = entry[1].text_content()
        app, created = models.Application.objects.get_or_create(name=name)
        print("Adding: %s" % name)
        app.save()
        #for link in entry.xpath('.//a'):
        #        report = models.Report()
        #        report.app = app
        #        report.title = "(autogenerated from Lcamtuf's page)"
        #        report.url = link.get('href')
        #        report.save()
