#!/usr/bin/env python

from lxml import html
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "fuzziverse.settings")
from fuzziverse import models

import django
django.setup()

t = html.parse("http://lcamtuf.coredump.cx/afl/")
TITLE = "(autogenerated from Lcamtuf's page)"
for entry in t.xpath('//td'):
        name = entry.text.strip()
        app, created = models.Application.objects.get_or_create(name=name)
        if created:
                print("Added: %s" % name)
        for link in entry.xpath('.//a'):
                args = {'app': app, 'title': TITLE, 'url': link.get('href')}
                report, created = models.Report.objects.get_or_create(**args)

ALSO_FUZZED_XPATH = '//p [contains(.,"On top of this")] /i'
also_fuzzed = {i.text_content() for i in t.xpath(ALSO_FUZZED_XPATH)}
for name in also_fuzzed:
        app, created = models.Application.objects.get_or_create(name=name)
        if created:
            print("Added: %s" % name)
        models.FuzzingAttempt.objects.get_or_create(app=app, notes=TITLE)
