#!/usr/bin/env python

from lxml import html
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "fuzziverse.settings")
from fuzziverse import models

import django
django.setup()

t = html.parse("http://lcamtuf.coredump.cx/afl/")
TITLE = "(autogenerated from Lcamtuf's page)"
for entry in t.xpath('//td'):
        name = entry.text.strip()
        app, created = models.Application.objects.get_or_create(name=name)
        print("Adding: %s" % name)
        for link in entry.xpath('.//a'):
                args = {'app': app, 'title': TITLE, 'url': link.get('href')}
                report, created = models.Report.objects.get_or_create(**args)
